<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>象棋走法推荐</title>

</head>
<body>

<form method="post" action="/upload" enctype="multipart/form-data">
    <input type="file" name="file" accept="image/*">
    <button type="submit">提交</button>
</form>

${action!''}

</body>
</html>
